############# English navigation ##############

# main menu
[[main]]
name = "TRANG CHỦ"
url = "/"
weight = 1

[[main]]
name = "WORKSHOP GỐM"
url = "/workshop-gom/"
weight = 2

[[main]]
name = "ẢNH WORKSHOP"
url = "https://drive.google.com/drive/u/0/folders/1dxhUJCzTqxvC7x7GAD7s8yFP2Z-FkT5K"
weight = 3

[[main]]
name = "VỀ CHÚNG TÔI"
url = "/about"
weight = 4

[[main]]
name = "LIÊN HỆ"
url = "/contact"
weight = 5

# footer menu
[[footer]]
name = "Về Từ Lâu Space"
url = "/about"
weight = 1

[[footer]]
name = "Đặt Lịch & Bảng Giá"
url = "/pages/booking-pricing"
weight = 2

[[footer]]
name = "Chính Sách & An Toàn"
url = "/pages/policies"
weight = 3

[[footer]]
name = "Private Workshop"
url = "/services/private-workshop"
weight = 4

[[footer]]
name = "Community Workshop"
url = "/services/community-workshop"
weight = 5

[[footer]]
name = "Corporate Workshop"
url = "/services/corporate-workshop"
weight = 6
